### PR TITLE
ethnode: Fix new geth nodeID format check

### LINKED ISSUE #65: ethnode: geth changed node input parsing, breaking admin_addTrustedPeer
Looks like geth added new checks to the way node inputs get parsed: https://github.com/ethereum/go-ethereum/pull/19663

Some of our users are getting:
> invalid enode: missing 'enr:' prefix for base64-encoded record

We were sending passing in just the Enode ID, but looks like it requires an `enode://` prefix to always be present now.

### PR DESCRIPTION
**Pull request by shazow**
- ethnode: Make sure nodeIDs start with `enode://`, fixes #65
- agent: Don't error fatally on AddPeer failures. Broken versions of vipnode agents will fail to whitelist, for example, but this should not break good agents. Opened #66 to improve this on the pool side.

### CODE REVIEW

File: ethnode/geth.go [hunk 1]
```diff
@@ -22,39 +33,26 @@ func (n *gethNode) Kind() NodeKind {
 	return Geth
 }
 
-func (n *gethNode) CheckCompatible(ctx context.Context) error {
-	// TODO: Make sure we have the necessary APIs available, maybe version check?
-	var result interface{}
-	err := n.client.CallContext(ctx, &result, "admin_addTrustedPeer", "")
```
Comment (shazow) [inline ethnode/geth.go]: Been about 1.5 years, safe to stop checking for it.
